name: Snyk
description: Run Snyk tests in your Buildkite pipelines
author: https://github.com/buildkite-plugins
public: true
requirements:
  - bash
  - snyk
  - snyk-to-html
configuration:
  properties:
    token-env:
      type: string
    org:
      type: string
    image:
      type: string
    scan:
      enum: [ "code", "container", "oss" ]
    annotate:
      type: boolean
    block:
      type: boolean
  required:
    - scan
  additionalProperties: false